### ISSUE TITLE
Add life cycle hooks and heartbeat (or healthcheck?) to graders

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieGrader#10]
https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html

Use lifecycle hooks to wait until current jobs have finished before terminating an instance.

https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html

**Comment by trombonekenny** [comment]
Seems like lifecycle hooks are the thing to use here, just beware the default 1 hour wait state.

**Comment by mwest1066** [comment]
Healthcheck was implemented in #28. We haven't got lifecycle hooks yet.

**Comment by nwalters512** [comment]
This repo is being archived. If this is still relevant, please recreate it in the [`PrairieLearn/PrairieLearn`](https://github.com/PrairieLearn/PrairieLearn) repository.
