### ISSUE TITLE
dos2unix the entrypoint script

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieGrader#138]
I supported a few situations this spring where Windows docker launches of externally graded questions didn't work because of the line encoding in the course entrypoint script. This is tricky to identify and resolve (it means the Windows system needs the Linux line endings, which GitHub clients actively works against).

I was thinking we might make PG automatically convert the entrypoint script to Linux line endings before it runs it. That would solve some support problems and I don't think would have a downside when run under Linux anyway?

**Comment by nwalters512** [comment]
This repo is being archived. If this is still relevant, please recreate it in the [`PrairieLearn/PrairieLearn`](https://github.com/PrairieLearn/PrairieLearn) repository.
