### ISSUE TITLE
Conceptual hamming distance between submitted code and functional code if 100% not awarded on programming exam

### ISSUE THREAD

**Issue by alichtman** [PrairieLearn/PrairieGrader#15]
Inspired by [this Reddit post](https://www.reddit.com/r/UIUC/comments/86w3fn/cs_225_is_making_me_feel_like_giving_up/)

This is a potential feature for administering programming exams.

For example, if the only error in submitted code is PBR instead of PBV, a student should get a score like 95%, not 50%.

Some issues with this are: 

1. There are always multiple approaches to any coding challenge. Potential solution: Use a set of common solutions, as opposed to one solution.

2. (Will add more later)

**Comment by nwalters512** [comment]
This is definitely an interesting idea, and it wouldn't require any changes from PL (or PrairieGrader) to implement. This makes much more sense to do on a per-course basis - I think it's best if PG remains completely agnostic to the code that it's excecuting. If you have a course that's interested in doing this, we'd be happy to work with them if they have any questions about implementation in the context of PL!
