### ISSUE TITLE
periodically delete old images

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieGrader#18]
Don't just delete containers, also delete old images. @jakebailey apparently has code (in Go) to do this correctly (need to be careful not to delete images that are being pulled).

**Comment by nwalters512** [comment]
This repo is being archived. If this is still relevant, please recreate it in the [`PrairieLearn/PrairieLearn`](https://github.com/PrairieLearn/PrairieLearn) repository.
