### ISSUE TITLE
docker failures don't fail the job correctly

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieGrader#46]
Grading jobs 9991246 and 9991257 both failed due to docker issues:
```
Error: connect ECONNREFUSED /var/run/docker.sock
Error: read ECONNRESET
```
But these jobs don't get reported as failed to PL (and aren't marked as failed in the DB).

**Comment by nwalters512** [comment]
This repo is being archived. If this is still relevant, please recreate it in the [`PrairieLearn/PrairieLearn`](https://github.com/PrairieLearn/PrairieLearn) repository.
